export enum CategoryIconEnum {
  BRIEFCASE_BUSINESS = 'BRIEFCASE_BUSINESS',
  CAR_FRONT = 'CAR_FRONT',
  HEART_PULSE = 'HEART_PULSE',
  PIGGY_BANK = 'PIGGY_BANK',
  SHOPPING_CART = 'SHOPPING_CART',
  TICKET = 'TICKET',
  TOOL_CASE = 'TOOL_CASE',
  UTENSILS = 'UTENSILS',
  PAW_PRINT = 'PAW_PRINT',
  HOUSE = 'HOUSE',
  GIFT = 'GIFT',
  DUMBBELL = 'DUMBBELL',
  BOOK_OPEN = 'BOOK_OPEN',
  BAGGAGE_CLAIM = 'BAGGAGE_CLAIM',
  MAILBOX = 'MAILBOX',
  RECEIPT_TEXT = 'RECEIPT_TEXT'
}
